package com.outsource.model;

public class Contract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.contract_id
     *
     * @mbggenerated Thu Feb 01 22:28:11 CST 2018
     */
    private Integer contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.contract_context
     *
     * @mbggenerated Thu Feb 01 22:28:11 CST 2018
     */
    private String contractContext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.contract_id
     *
     * @return the value of contract.contract_id
     *
     * @mbggenerated Thu Feb 01 22:28:11 CST 2018
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.contract_id
     *
     * @param contractId the value for contract.contract_id
     *
     * @mbggenerated Thu Feb 01 22:28:11 CST 2018
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.contract_context
     *
     * @return the value of contract.contract_context
     *
     * @mbggenerated Thu Feb 01 22:28:11 CST 2018
     */
    public String getContractContext() {
        return contractContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.contract_context
     *
     * @param contractContext the value for contract.contract_context
     *
     * @mbggenerated Thu Feb 01 22:28:11 CST 2018
     */
    public void setContractContext(String contractContext) {
        this.contractContext = contractContext;
    }
}