package com.outsource.out.model;

public class Dog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dog.id
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dog.name
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dog.age
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dog.id
     *
     * @return the value of dog.id
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dog.id
     *
     * @param id the value for dog.id
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dog.name
     *
     * @return the value of dog.name
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dog.name
     *
     * @param name the value for dog.name
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dog.age
     *
     * @return the value of dog.age
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dog.age
     *
     * @param age the value for dog.age
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}