package com.outsource.model;

public class Files {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column files.file_id
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column files.file_name
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column files.file_state
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    private Integer fileState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column files.file_id
     *
     * @return the value of files.file_id
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column files.file_id
     *
     * @param fileId the value for files.file_id
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column files.file_name
     *
     * @return the value of files.file_name
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column files.file_name
     *
     * @param fileName the value for files.file_name
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column files.file_state
     *
     * @return the value of files.file_state
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    public Integer getFileState() {
        return fileState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column files.file_state
     *
     * @param fileState the value for files.file_state
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    public void setFileState(Integer fileState) {
        this.fileState = fileState;
    }
}