package com.outsource.model;

public class Project_File {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file.project_file_id
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    private Integer projectFileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file.project_id
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_file.file_id
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    private Integer fileId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file.project_file_id
     *
     * @return the value of project_file.project_file_id
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    public Integer getProjectFileId() {
        return projectFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file.project_file_id
     *
     * @param projectFileId the value for project_file.project_file_id
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    public void setProjectFileId(Integer projectFileId) {
        this.projectFileId = projectFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file.project_id
     *
     * @return the value of project_file.project_id
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file.project_id
     *
     * @param projectId the value for project_file.project_id
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_file.file_id
     *
     * @return the value of project_file.file_id
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_file.file_id
     *
     * @param fileId the value for project_file.file_id
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }
}