package com.outsource.model;

public class Project_User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_user.project_user_id
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    private Integer projectUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_user.user_id
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_user.project_id
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    private Integer projectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_user.project_user_id
     *
     * @return the value of project_user.project_user_id
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    public Integer getProjectUserId() {
        return projectUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_user.project_user_id
     *
     * @param projectUserId the value for project_user.project_user_id
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    public void setProjectUserId(Integer projectUserId) {
        this.projectUserId = projectUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_user.user_id
     *
     * @return the value of project_user.user_id
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_user.user_id
     *
     * @param userId the value for project_user.user_id
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_user.project_id
     *
     * @return the value of project_user.project_id
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_user.project_id
     *
     * @param projectId the value for project_user.project_id
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
}