package com.outsource.model;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_id
     *
     * @mbggenerated Tue Jan 30 16:40:16 CST 2018
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbggenerated Tue Jan 30 16:40:16 CST 2018
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_desc
     *
     * @mbggenerated Tue Jan 30 16:40:16 CST 2018
     */
    private String projectDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_id
     *
     * @return the value of project.project_id
     *
     * @mbggenerated Tue Jan 30 16:40:16 CST 2018
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_id
     *
     * @param projectId the value for project.project_id
     *
     * @mbggenerated Tue Jan 30 16:40:16 CST 2018
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_name
     *
     * @return the value of project.project_name
     *
     * @mbggenerated Tue Jan 30 16:40:16 CST 2018
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_name
     *
     * @param projectName the value for project.project_name
     *
     * @mbggenerated Tue Jan 30 16:40:16 CST 2018
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_desc
     *
     * @return the value of project.project_desc
     *
     * @mbggenerated Tue Jan 30 16:40:16 CST 2018
     */
    public String getProjectDesc() {
        return projectDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_desc
     *
     * @param projectDesc the value for project.project_desc
     *
     * @mbggenerated Tue Jan 30 16:40:16 CST 2018
     */
    public void setProjectDesc(String projectDesc) {
        this.projectDesc = projectDesc;
    }
}