package com.outsource.model;

public class Task {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_id
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_outline
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    private String taskOutline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_desc
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    private String taskDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_state
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    private Integer taskState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_executor
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    private String taskExecutor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_projectid
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    private Integer taskProjectid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_id
     *
     * @return the value of task.task_id
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_id
     *
     * @param taskId the value for task.task_id
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_outline
     *
     * @return the value of task.task_outline
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    public String getTaskOutline() {
        return taskOutline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_outline
     *
     * @param taskOutline the value for task.task_outline
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    public void setTaskOutline(String taskOutline) {
        this.taskOutline = taskOutline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_desc
     *
     * @return the value of task.task_desc
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    public String getTaskDesc() {
        return taskDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_desc
     *
     * @param taskDesc the value for task.task_desc
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    public void setTaskDesc(String taskDesc) {
        this.taskDesc = taskDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_state
     *
     * @return the value of task.task_state
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    public Integer getTaskState() {
        return taskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_state
     *
     * @param taskState the value for task.task_state
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    public void setTaskState(Integer taskState) {
        this.taskState = taskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_executor
     *
     * @return the value of task.task_executor
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    public String getTaskExecutor() {
        return taskExecutor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_executor
     *
     * @param taskExecutor the value for task.task_executor
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    public void setTaskExecutor(String taskExecutor) {
        this.taskExecutor = taskExecutor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_projectid
     *
     * @return the value of task.task_projectid
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    public Integer getTaskProjectid() {
        return taskProjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_projectid
     *
     * @param taskProjectid the value for task.task_projectid
     *
     * @mbggenerated Thu Feb 01 22:31:09 CST 2018
     */
    public void setTaskProjectid(Integer taskProjectid) {
        this.taskProjectid = taskProjectid;
    }
}