package com.outsource.model;

public class User_Contract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_contract.user_contract_id
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    private Integer userContractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_contract.user_id
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_contract.contract_id
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    private Integer contractId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_contract.user_contract_id
     *
     * @return the value of user_contract.user_contract_id
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    public Integer getUserContractId() {
        return userContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_contract.user_contract_id
     *
     * @param userContractId the value for user_contract.user_contract_id
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    public void setUserContractId(Integer userContractId) {
        this.userContractId = userContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_contract.user_id
     *
     * @return the value of user_contract.user_id
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_contract.user_id
     *
     * @param userId the value for user_contract.user_id
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_contract.contract_id
     *
     * @return the value of user_contract.contract_id
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_contract.contract_id
     *
     * @param contractId the value for user_contract.contract_id
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }
}