package com.outsource.out.dao;

import com.outsource.out.model.Dog;
import com.outsource.out.model.DogExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    int countByExample(DogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    int deleteByExample(DogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    int insert(Dog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    int insertSelective(Dog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    List<Dog> selectByExample(DogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    Dog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") Dog record, @Param("example") DogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    int updateByExample(@Param("record") Dog record, @Param("example") DogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    int updateByPrimaryKeySelective(Dog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbggenerated Wed Jan 24 17:41:49 CST 2018
     */
    int updateByPrimaryKey(Dog record);
}