package com.outsource.dao;

import com.outsource.model.Files;
import com.outsource.model.FilesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    int countByExample(FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    int deleteByExample(FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    int deleteByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    int insert(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    int insertSelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    List<Files> selectByExample(FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    Files selectByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") Files record, @Param("example") FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    int updateByExample(@Param("record") Files record, @Param("example") FilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    int updateByPrimaryKeySelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated Tue Jan 30 14:23:26 CST 2018
     */
    int updateByPrimaryKey(Files record);
}