package com.outsource.dao;

import com.outsource.model.Project_File;
import com.outsource.model.Project_FileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Project_FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    int countByExample(Project_FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    int deleteByExample(Project_FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    int deleteByPrimaryKey(Integer projectFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    int insert(Project_File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    int insertSelective(Project_File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    List<Project_File> selectByExample(Project_FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    Project_File selectByPrimaryKey(Integer projectFileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") Project_File record, @Param("example") Project_FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    int updateByExample(@Param("record") Project_File record, @Param("example") Project_FileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    int updateByPrimaryKeySelective(Project_File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_file
     *
     * @mbggenerated Thu Feb 01 22:30:20 CST 2018
     */
    int updateByPrimaryKey(Project_File record);
}