package com.outsource.dao;

import com.outsource.model.Project_User;
import com.outsource.model.Project_UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Project_UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    int countByExample(Project_UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    int deleteByExample(Project_UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    int deleteByPrimaryKey(Integer projectUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    int insert(Project_User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    int insertSelective(Project_User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    List<Project_User> selectByExample(Project_UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    Project_User selectByPrimaryKey(Integer projectUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") Project_User record, @Param("example") Project_UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    int updateByExample(@Param("record") Project_User record, @Param("example") Project_UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    int updateByPrimaryKeySelective(Project_User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_user
     *
     * @mbggenerated Thu Feb 01 22:30:43 CST 2018
     */
    int updateByPrimaryKey(Project_User record);
}