package com.outsource.dao;

import com.outsource.model.User_Contract;
import com.outsource.model.User_ContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface User_ContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_contract
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    int countByExample(User_ContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_contract
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    int deleteByExample(User_ContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_contract
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    int deleteByPrimaryKey(Integer userContractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_contract
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    int insert(User_Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_contract
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    int insertSelective(User_Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_contract
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    List<User_Contract> selectByExample(User_ContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_contract
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    User_Contract selectByPrimaryKey(Integer userContractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_contract
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") User_Contract record, @Param("example") User_ContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_contract
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    int updateByExample(@Param("record") User_Contract record, @Param("example") User_ContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_contract
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    int updateByPrimaryKeySelective(User_Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_contract
     *
     * @mbggenerated Thu Feb 01 22:40:07 CST 2018
     */
    int updateByPrimaryKey(User_Contract record);
}